#
# Copyright (c) 2017 OBiBa. All rights reserved.
#
# This program and the accompanying materials
# are made available under the terms of the GNU Public License v3.0.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#
# Human readable information about the plugin (required)
#
name=mica-search-os2
type=mica-search
title=Mica Search OpenSearch
description=Mica search engine based on OpenSearch ${opensearch.version}. Requires a running OpenSearch instance.
author=OBiBa
maintainer=dev@obiba.org
license=GPL-3
website=http://obiba.org
version=${project.version}
# version of mica that was used for plugin development
mica.version=${mica.version}

#
# Settings
#
# OpenSearch version (do not override)
opensearch.version=${opensearch.version}
# Use the Transport Client (i.e. connect to an OpenSearch cluster) instead of the Node Client.
transportClient=false
# Comma separated entry points (IP and port) to an OpenSearch cluster. Default is localhost:9200.
transportAddresses=
# Specifies that the Transport Client will collect IP addresses from nodes in an OpenSearch cluster.
transportSniff=false
